framework:
    cache:
        default_redis_provider: 'redis://redis:6379'

        pools:
            cache.exchange_rates:
                adapter: cache.adapter.redis_tag_aware
                provider: '%env(REDIS_URL)%'
                tags: true