framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://localhost'
        
        pools:
            exchange_rates.cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 3600
                tags: true