framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            cache.exchange_rates:
                adapter: cache.adapter.redis
                public: true
                default_lifetime: 3600
                tags: true