# config/packages/monolog.yaml
monolog:
  handlers:
    main:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
      max_files: 10
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]