services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Client\CBRClient:
        arguments:
            $httpClient: '@http_client'
            $logger: '@logger'

    App\Service\CBR\CBRService:
        arguments:
            $cbrClient: '@App\Client\CBRClient'
            $entityManager: '@doctrine.orm.entity_manager'
            $cache: '@cache.exchange_rates'
            $logger: '@logger'

    App\Repository\ExchangeRateRepository:
        arguments:
            $cache: '@cache.exchange_rates'

    App\Controller\Api\ExchangeRateController:
        arguments:
            $rateRepository: '@App\Repository\ExchangeRateRepository'
            $validator: '@validator'
            $requestFactory: '@App\Factory\HistoricalRatesRequestFactory'
            $exchangeRatesConfig: '%exchange_rates%'

    App\Controller\Api\ConfigController:
        arguments:
            $exchangeRatesConfig: '%exchange_rates%'

    App\Command\UpdateExchangeRatesCommand:
        arguments:
            $cbrService: '@App\Service\CBR\CBRService'
            $exchangeRatesConfig: '%exchange_rates%'