services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Client\CBRClient:
        arguments:
            $httpClient: '@http_client'
            $logger: '@logger'

    App\Service\CBR\CBRService:
        arguments:
            $cbrClient: '@App\Client\CBRClient'
            $entityManager: '@doctrine.orm.entity_manager'
            $cache: '@App\Service\RedisCacheService'
            $logger: '@logger'

    App\Repository\ExchangeRateRepository:
        arguments:
            $cache: '@exchange_rates.cache'